# Generated by Django 5.1.5 on 2025-01-20 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0002_remove_proveedor_servicios_ofrecidos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='role',
            new_name='rol',
        ),
    ]
